# Generated by Django 3.2.5 on 2022-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newsletterrecipients_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipients',
            name='lastname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
